 .../debian-anland.yml        |   15 [32m+[m[31m-[m
 .../.clang-format            |   65 [31m-[m
 .../.clang-tidy              |  101 [31m-[m
 .../workflows/nix.yml        |   17 [31m-[m
 aquamarine-0.12.1/.gitignore |   39 [31m-[m
 .../CMakeLists.txt           |  155 [31m-[m
 aquamarine-0.12.1/LICENSE    |   28 [31m-[m
 aquamarine-0.12.1/README.md  |   22 [31m-[m
 aquamarine-0.12.1/VERSION    |    1 [31m-[m
 .../aquamarine.pc.in         |   10 [31m-[m
 .../data/hwdata.hpp.in       |    8 [31m-[m
 .../data/hwdata.sh           |    8 [31m-[m
 .../debian/changelog         |   94 [31m-[m
 .../debian/control           |   74 [31m-[m
 .../debian/copyright         |   40 [31m-[m
 .../debian/gbp.conf          |    4 [31m-[m
 ...libaquamarine-dev.install |    3 [31m-[m
 .../libaquamarine11.install  |    1 [31m-[m
 ...otocol-and-producer.patch |  974 [31m-[m
 ...nd-dmabuf-allocator.patch |  744 [31m-[m
 ...-input-and-gestures.patch |  509 [31m-[m
 ...Anland-audio-bridge.patch |  626 [31m-[m
 ...nland-camera-bridge.patch |  927 [31m-[m
 ...d-and-build-support.patch | 6912 [31m------[m
 ...-pointer-conversion.patch |   22 [31m-[m
 ...-pointer-conversion.patch |   17 [31m-[m
 ...de-unistd-for-close.patch |   17 [31m-[m
 ...ling-optional-tests.patch |   32 [31m-[m
 .../debian/patches/series    |   10 [31m-[m
 .../debian/rules             |   18 [31m-[m
 .../debian/salsa-ci.yml      |    3 [31m-[m
 .../debian/source/format     |    1 [31m-[m
 .../debian/upstream/metadata |    5 [31m-[m
 .../debian/watch             |    5 [31m-[m
 .../docs/env.md              |   14 [31m-[m
 aquamarine-0.12.1/flake.lock |   91 [31m-[m
 aquamarine-0.12.1/flake.nix  |   58 [31m-[m
 .../allocator/Allocator.hpp  |   32 [31m-[m
 .../allocator/DRMDumb.hpp    |   68 [31m-[m
 .../allocator/GBM.hpp        |   71 [31m-[m
 .../allocator/Swapchain.hpp  |   54 [31m-[m
 .../AnlandBackend.hpp        |  151 [31m-[m
 .../backend/AnlandOutput.hpp |   60 [31m-[m
 .../backend/Backend.hpp      |  191 [31m-[m
 .../backend/DRM.hpp          |  496 [31m-[m
 .../backend/Headless.hpp     |   87 [31m-[m
 .../backend/Misc.hpp         |   17 [31m-[m
 .../backend/Null.hpp         |   45 [31m-[m
 .../backend/Session.hpp      |  249 [31m-[m
 .../backend/Wayland.hpp      |  196 [31m-[m
 .../backend/drm/Atomic.hpp   |   49 [31m-[m
 .../backend/drm/Legacy.hpp   |   19 [31m-[m
 .../buffer/Buffer.hpp        |   77 [31m-[m
 .../input/Input.hpp          |  391 [31m-[m
 .../misc/Attachment.hpp      |   50 [31m-[m
 .../output/Output.hpp        |  221 [31m-[m
 .../nix/default.nix          |   87 [31m-[m
 .../nix/overlays.nix         |   39 [31m-[m
 .../protocols/.gitkeep       |    0
 .../allocator/Allocator.cpp  |    3 [31m-[m
 .../allocator/DRMDumb.cpp    |  159 [31m-[m
 .../src/allocator/GBM.cpp    |  392 [31m-[m
 .../allocator/Swapchain.cpp  |  142 [31m-[m
 .../src/backend/Backend.cpp  |  394 [31m-[m
 .../src/backend/Headless.cpp |  260 [31m-[m
 .../src/backend/Logger.cpp   |   35 [31m-[m
 .../src/backend/Logger.hpp   |   37 [31m-[m
 .../src/backend/Null.cpp     |   89 [31m-[m
 .../src/backend/Session.cpp  | 1216 [31m-[m
 .../src/backend/Wayland.cpp  |  834 [31m-[m
 .../AnlandAllocator.hpp      |  232 [31m-[m
 .../anland/AnlandBackend.cpp |  660 [31m-[m
 .../anland/AnlandGesture.hpp |  232 [31m-[m
 .../anland/AnlandInput.cpp   |  259 [31m-[m
 .../anland/AnlandOutput.cpp  |  364 [31m-[m
 .../anland/anland_audio.c    |  568 [31m-[m
 .../anland/anland_audio.h    |   41 [31m-[m
 .../anland/anland_camera.c   |  856 [31m-[m
 .../anland/anland_camera.h   |   54 [31m-[m
 .../display_producer.c       |  506 [31m-[m
 .../display_producer.h       |   82 [31m-[m
 .../anland/protocol.h        |  210 [31m-[m
 .../anland/socket_utils.c    |  121 [31m-[m
 .../anland/socket_utils.h    |   18 [31m-[m
 .../src/backend/drm/DRM.cpp  | 2707 [31m--[m
 .../src/backend/drm/Math.cpp |  207 [31m-[m
 .../src/backend/drm/Math.hpp |   18 [31m-[m
 .../backend/drm/Props.cpp    |  227 [31m-[m
 .../backend/drm/Props.hpp    |   14 [31m-[m
 .../backend/drm/Renderer.cpp | 1195 [31m-[m
 .../backend/drm/Renderer.hpp |  186 [31m-[m
 .../drm/impl/Atomic.cpp      |  556 [31m-[m
 .../drm/impl/Legacy.cpp      |  172 [31m-[m
 .../src/buffer/Buffer.cpp    |   41 [31m-[m
 .../include/FormatUtils.hpp  |    7 [31m-[m
 .../src/include/Shared.hpp   |   29 [31m-[m
 .../src/input/Input.cpp      |   37 [31m-[m
 .../src/misc/Attachment.cpp  |   21 [31m-[m
 .../src/output/Output.cpp    |  148 [31m-[m
 .../utils/FormatUtils.cpp    |   18 [31m-[m
 .../src/utils/Shared.cpp     |   18 [31m-[m
 .../tests/Attachments.cpp    |   64 [31m-[m
 .../tests/SimpleWindow.cpp   |   91 [31m-[m
 .../tests/shared.hpp         |   20 [31m-[m
 build-anland.sh              |   53 [32m+[m[31m-[m
 debian/control               |    4 [32m+[m[31m-[m
 debian/patches/series        |    5 [32m+[m[31m-[m
 debian/rules                 |   18 [32m+[m[31m-[m
 install-anland-desktop.sh    |  169 [32m+[m[31m-[m
 109 files changed, 218 insertions(+), 27891 deletions(-)
