#!/bin/sh
# Configure the official AvengeMedia repositories and install a downloaded
# Anland Hyprland artifact set. Run from the artifact directory, or pass it as
# the first argument:
#   ./install-anland-desktop.sh /path/to/anland-debian-packages-arm64
# The artifact contains only locally built Hyprland-side packages. DMS and the
# complete official runtime are resolved from AvengeMedia/Debian APT sources.
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
artifact_dir=${1:-$script_dir}
artifact_dir=$(CDPATH= cd -- "$artifact_dir" && pwd)

if [ "$(dpkg --print-architecture)" != arm64 ]; then
    echo "install-anland-desktop: this artifact set requires an arm64 Debian system" >&2
    exit 2
fi

find_one() {
    pattern=$1
    matches=$(find "$artifact_dir" -maxdepth 1 -type f -name "$pattern" -print)
    count=$(printf '%s\n' "$matches" | sed '/^$/d' | wc -l)
    if [ "$count" -ne 1 ]; then
        echo "install-anland-desktop: expected exactly one $pattern in $artifact_dir (found $count)" >&2
        exit 2
    fi
    printf '%s\n' "$matches"
}
hyprland_deb=$(find_one 'hyprland_*_arm64.deb')
desktop_deb=$(find_one 'hyprland-anland-desktop_*_arm64.deb')
aquamarine_deb=$(find_one 'libaquamarine13_*_arm64.deb')
xwayland_deb=$(find_one 'xwayland_*_arm64.deb')


if [ -f "$artifact_dir/SHA256SUMS" ]; then
    (
        cd "$artifact_dir"
        sha256sum -c SHA256SUMS
    )
fi

# DMS itself is from the dms repository; its DankLinux runtime components
# (including danksearch, dgop and matugen) are from the second repository.
sudo env DEBIAN_FRONTEND=noninteractive apt-get update
sudo env DEBIAN_FRONTEND=noninteractive apt-get reinstall -y --no-install-recommends \
    ca-certificates curl
sudo install -d -m 0755 /etc/apt/keyrings
sudo curl --fail --location --retry 3 \
    --output /etc/apt/keyrings/avengemedia-dms.asc \
    https://download.opensuse.org/repositories/home:/AvengeMedia:/dms/Debian_Unstable/Release.key
sudo curl --fail --location --retry 3 \
    --output /etc/apt/keyrings/avengemedia-danklinux.asc \
    https://download.opensuse.org/repositories/home:/AvengeMedia:/danklinux/Debian_Unstable/Release.key

sudo tee /etc/apt/sources.list.d/avengemedia-dms.sources >/dev/null <<'EOF'
Types: deb
URIs: https://download.opensuse.org/repositories/home:/AvengeMedia:/dms/Debian_Unstable/
Suites: /
Signed-By: /etc/apt/keyrings/avengemedia-dms.asc
EOF
sudo tee /etc/apt/sources.list.d/avengemedia-danklinux.sources >/dev/null <<'EOF'
Types: deb
URIs: https://download.opensuse.org/repositories/home:/AvengeMedia:/danklinux/Debian_Unstable/
Suites: /
Signed-By: /etc/apt/keyrings/avengemedia-danklinux.asc
EOF

sudo env DEBIAN_FRONTEND=noninteractive apt-get update
# Install the locally built compositor stack and the complete set of official
# Hyprland session components used by a normal DMS/Hyprland desktop. DMS is not
# carried in the artifact: the metapackage dependency resolves dms itself, and
# its complete runtime closure, from the AvengeMedia repositories above.
sudo env DEBIAN_FRONTEND=noninteractive apt-get reinstall -y --allow-downgrades \
    "$aquamarine_deb" \
    "$hyprland_deb" \
    "$xwayland_deb" \
    "$desktop_deb" \
    hypridle \
    hyprlock \
    hyprpaper \
    hyprpicker \
    hyprpolkitagent \
    hyprsunset \
    xdg-desktop-portal-hyprland \
    xdg-desktop-portal-gtk \
    hyprland-guiutils

# Hyprgrass is shipped inside the ABI-matched hyprland Debian package. Inject
# only a marked, replaceable Lua block; existing user configuration is preserved.
config_home=${XDG_CONFIG_HOME:-"$HOME/.config"}
hypr_config_dir="$config_home/hypr"
hypr_config="$hypr_config_dir/hyprland.lua"
if command -v dpkg-architecture >/dev/null 2>&1; then
    plugin_multiarch=$(dpkg-architecture -qDEB_HOST_MULTIARCH)
elif [ "$(dpkg --print-architecture 2>/dev/null)" = "arm64" ]; then
    plugin_multiarch=aarch64-linux-gnu
else
    echo "install-anland-desktop: dpkg-architecture is required to locate the Hyprgrass plugin" >&2
    exit 2
fi
hyprgrass_target="/usr/lib/$plugin_multiarch/hyprland/plugins/libhyprgrass.so"

if [ ! -r "$hyprgrass_target" ]; then
    echo "install-anland-desktop: Hyprgrass is missing from the installed hyprland package: $hyprgrass_target" >&2
    exit 2
fi

if [ ! -e "$hypr_config" ]; then
    mkdir -p "$hypr_config_dir"

    # Hyprland generates its embedded default configuration when asked to verify
    # a missing explicit config path.  A private runtime directory avoids using
    # or creating a real compositor socket during installation.
    runtime_dir=$(mktemp -d "${TMPDIR:-/tmp}/anland-hyprland-runtime.XXXXXX")
    if XDG_RUNTIME_DIR="$runtime_dir" Hyprland --config "$hypr_config" --verify-config; then
        :
    else
        rc=$?
        rm -rf "$runtime_dir"
        echo "install-anland-desktop: Hyprland could not generate $hypr_config (exit $rc)" >&2
        exit "$rc"
    fi
    rm -rf "$runtime_dir"

    # Remove the autogenerated-warning marker as requested, switch the default
    # main modifier to Alt, retain exactly three persistent initial workspaces,
    # and append the complete Anland touch-gesture profile and documentation.
    sed -i '/^[[:space:]]*hl\.config({ autogenerated = true })/d' "$hypr_config"
    sed -i 's/local mainMod = "SUPER"/local mainMod = "ALT"/' "$hypr_config"
    # The generated configuration already defines the three-finger horizontal
    # workspace gesture.  Keep it and add the remaining Anland gestures below.

    cat >>"$hypr_config" <<'EOF'

-- --------------------------------------------------------------------------
-- Anland desktop defaults / Anland 桌面默认设置
-- --------------------------------------------------------------------------
-- Keep three initial workspaces available.
-- 保持三个初始工作区可用。
hl.workspace_rule({ workspace = "1", persistent = true, default = true })
hl.workspace_rule({ workspace = "2", persistent = true })
hl.workspace_rule({ workspace = "3", persistent = true })

-- Anland touch gestures / Anland 触屏手势
-- Three fingers horizontally: switch workspaces (kept from Hyprland default).
-- 三指水平滑动：切换工作区（保留 Hyprland 已生成的默认配置）。
-- Three fingers up: toggle fullscreen for the focused window.
-- 三指上滑：切换当前焦点窗口的全屏状态。
hl.gesture({ fingers = 3, direction = "up", action = "fullscreen", mode = "toggle" })
-- Three fingers down: toggle floating for the focused window.
-- 三指下滑：切换当前焦点窗口的浮动状态。
hl.gesture({ fingers = 3, direction = "down", action = "float", mode = "toggle" })
-- Four fingers down: open the special workspace named "magic".
-- 四指下滑：打开名为“magic”的特殊工作区。
hl.gesture({ fingers = 4, direction = "down", action = "special", workspace_name = "magic" })
-- Four fingers up: close the focused window.
-- 四指上滑：关闭当前焦点窗口。
hl.gesture({ fingers = 4, direction = "up", action = "close" })
-- Two-finger pinch: live cursor zoom.
-- 双指捏合：实时放大或缩小光标附近画面。
hl.gesture({ fingers = 2, direction = "pinch", action = "cursorZoom", zoom_level = "1", mode = "live" })

-- Note: In Anland app settings, Relative Mouse Mode can also emit these
-- gestures using a mouse. 触屏手势以外，Anland 软件设置中的“相对模式鼠标”
-- 也可以用鼠标触发上述手势。
EOF

    echo "install-anland-desktop: created Anland Lua configuration: $hypr_config"
else
    echo "install-anland-desktop: preserving existing Hyprland configuration: $hypr_config"
fi

# Replace only our own marked block. This makes upgrades idempotent and leaves
# all user-owned configuration untouched.
sed -i '/^-- BEGIN ANLAND HYPRGRASS/,/^-- END ANLAND HYPRGRASS/d' "$hypr_config"
cat >>"$hypr_config" <<EOF

-- BEGIN ANLAND HYPRGRASS
-- Bundled Hyprgrass touchscreen profile / 随附 Hyprgrass 触屏配置
hl.plugin.load("$hyprgrass_target")

-- Plugin functions/config values become available after the first config pass.
-- Hyprgrass reloads the config after registering them, so this guard makes the
-- initial startup valid and activates the profile on that automatic reload.
if hl.plugin.hyprgrass then
    -- Tablet defaults recommended by Hyprgrass / Hyprgrass 推荐的平板默认值
    hl.config({
        plugin = {
            hyprgrass = {
                sensitivity = 4.0,
                long_press_delay = 400,
                resize_on_border_long_press = true,
                edge_margin = 10,
            },
        },
        gestures = {
            workspace_swipe_touch = true,
            workspace_swipe_cancel_ratio = 0.15,
        },
    })

    -- Hyprgrass touchscreen gestures / Hyprgrass 触屏手势
    -- 3 fingers: workspace, fullscreen, floating / 三指：工作区、全屏、浮动
    hl.plugin.hyprgrass.gesture { pattern = {kind = "swipe", fingers = 3, direction = "horizontal"}, action = "workspace" }
    hl.plugin.hyprgrass.gesture { pattern = {kind = "swipe", fingers = 3, direction = "up"}, action = "fullscreen", mode = "toggle" }
    hl.plugin.hyprgrass.gesture { pattern = {kind = "swipe", fingers = 3, direction = "down"}, action = "float", mode = "toggle" }
    -- 4 fingers: special workspace and close / 四指：特殊工作区和关闭窗口
    hl.plugin.hyprgrass.gesture { pattern = {kind = "swipe", fingers = 4, direction = "down"}, action = "special", workspace_name = "magic" }
    hl.plugin.hyprgrass.gesture { pattern = {kind = "swipe", fingers = 4, direction = "up"}, action = "close" }
    -- Edge and long press / 边缘滑动和长按
    hl.plugin.hyprgrass.bind { pattern = {kind = "edge", origin = "left", direction = "right"}, action = hl.dsp.focus({workspace = "+1"}) }
    hl.plugin.hyprgrass.bind { pattern = {kind = "edge", origin = "right", direction = "left"}, action = hl.dsp.focus({workspace = "-1"}) }
    hl.plugin.hyprgrass.bind { pattern = {kind = "longpress", fingers = 1}, action = hl.dsp.window.drag(), mouse = true }
end
-- END ANLAND HYPRGRASS
EOF

echo "install-anland-desktop: installed Hyprgrass plugin: $hyprgrass_target"

cat <<'EOF'

Anland Hyprland desktop installed.

Touch gestures / 触屏手势:
  • 3-finger horizontal swipe: switch workspaces.
    三指水平滑动：切换工作区。
  • 3-finger swipe up: toggle fullscreen for the focused window.
    三指上滑：切换当前焦点窗口的全屏状态。
  • 3-finger swipe down: toggle floating for the focused window.
    三指下滑：切换当前焦点窗口的浮动状态。
  • 4-finger swipe down: open the "magic" special workspace.
    四指下滑：打开“magic”特殊工作区。
  • 4-finger swipe up: close the focused window.
    四指上滑：关闭当前焦点窗口。
  • 2-finger pinch: live cursor zoom.
    双指捏合：实时缩放光标附近的画面。

Tip / 提示:
  In Anland app settings, Relative Mouse Mode can also trigger these gestures
  with a mouse.
  在 Anland 软件设置中开启“相对模式鼠标”后，也可以用鼠标触发上述手势。

Start command / 启动命令:
  start-hyprland-anland
  Run this command to start the Anland Hyprland desktop session.
  运行此命令即可启动 Anland Hyprland 桌面会话。
EOF